### ISSUE TITLE
Use stable version of the plugin

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/kcptun-android#1]
We should use `0.0.1` without `-SNAPSHOT`. Stable version isn't subject to change and guarantees reproducible builds.

**Comment by madeye** [comment]
Should I first publish a stable version first?

**Comment by Mygod** [comment]
Yes. It's in `beta` branch. IIRC you need to call `sbt sonatypeRelease`.

**Comment by Mygod** [comment]
3b7ce5819d129d9b261f3d3cd9ae671c97176b11
