### ISSUE TITLE
请问如何配置

### ISSUE THREAD

**Issue by iciness** [shadowsocks/kcptun-android#11]
旧版中工作正常，但是插件化后一直无法配置成功

**Comment by Mygod** [comment]
1. Use remote port as KCP port;
2. Supply configs [like this](https://github.com/shadowsocks/kcptun-android/blob/v0.0.3/src/main/AndroidManifest.xml#L25): `crypt=none;mode=normal;mtu=1200;nocomp;dscp=46;parityshard=0`.

**Comment by iciness** [comment]
我服务器端只设置了--mode fast2 --key xxxxx 
参数这里是否只需要mode=fast2; key=xxxxx
另外我ss是开启udp的

**Comment by Mygod** [comment]
Yes. UDP forwarding doesn't work for now.

**Comment by iciness** [comment]
谢谢
