### ISSUE TITLE
乐视(EUI)系统无法识别插件

### ISSUE THREAD

**Issue by aUsernameWoW** [shadowsocks/kcptun-android#12]
![kcptunerror0](https://cloud.githubusercontent.com/assets/25660515/22779209/d17401ce-eef4-11e6-9b56-5c237cdd150d.png)
![kcptunerror1](https://cloud.githubusercontent.com/assets/25660515/22779211/d179b970-eef4-11e6-9a61-fe2754f94c1e.png)
![kcptunerror2](https://cloud.githubusercontent.com/assets/25660515/22779210/d1752928-eef4-11e6-97b0-042bdfcedade.png)

**Comment by aUsernameWoW** [comment]
EUI 5.8.017S_12291
Based on Android 6.0.1

**Comment by Mygod** [comment]
Your system is blocking plugins (`ActivityManager: don't allow to start` seems to be a feature of Huawei's ROMs). Check your system settings in hope of resolving this issue.

**Comment by mountainguan** [comment]
@aUsernameWoW flyme6也可以这样解决,感谢!

**Comment by john564** [comment]
works fine for a few weeks, but now gives unknown plugin, work-around, uninstall kcptun and install kcptun,  will be ok first time you connect with it, disconnect shadowsocks, next time you try to connect, again unknown plugin kcptun.
android 6.0 huawei
