### ISSUE TITLE
remote port 是什么意思，ss的remote port?还是kcptun的参数里可以使用remote port

### ISSUE THREAD

**Issue by zhaorenjie110** [shadowsocks/kcptun-android#16]
thanks,can you provide wiki?
thanks again..

**Comment by haodong** [comment]
Same concert that no place to submit kcptun's port.

**Comment by Mygod** [comment]
Use remote port as kcptun port.

**Comment by zhaorenjie110** [comment]
ohh...
![image](https://cloud.githubusercontent.com/assets/9960574/23840108/650cafac-07dd-11e7-93bd-66f96b229d77.png)
if need kcptun ,you must use kcp port replace ss port

**Comment by haodong** [comment]
not convenient

**Comment by Mygod** [comment]
Use multiple profiles.
