### ISSUE TITLE
Unknown plugin kcptun

### ISSUE THREAD

**Issue by haodong** [shadowsocks/kcptun-android#17]
The plugin has been successfully installed.
For profile A and B:
- A can start running with kcptun (although not successful and I'm still debugging with B) 
- B cannot start, carrying with an error `failed to connect the remote server: Unknown plugin kcptun`.
```
03-10 21:39:27.326  1019  1030 I HwPFWLogger: AppAutoStartupPolicy:prevent start provider of package com.github.shadowsocks.plugin.kcptun, auth: com.github.shadowsocks.plugin.kcptun.BinaryProvider, name: com.github.shadowsocks.plugin.kcptun.BinaryProvider by callerPid 15744, callerUid 10089
03-10 21:39:27.328 15744 16330 W System.err: java.lang.IllegalArgumentException: Unknown URI content://com.github.shadowsocks.plugin.kcptun.BinaryProvider
03-10 21:39:27.330  1019  1831 I HwPFWLogger: AppAutoStartupPolicy:prevent start provider of package com.github.shadowsocks.plugin.kcptun, auth: com.github.shadowsocks.plugin.kcptun.BinaryProvider, name: com.github.shadowsocks.plugin.kcptun.BinaryProvider by callerPid 15744, callerUid 10089
03-10 21:39:27.344 15744 16330 W System.err: java.io.FileNotFoundException: Unknown plugin kcptun
03-10 21:39:27.393 15784 15784 E ShadowsocksMainActivity: Error to start VPN service: Failed to connect the remote server: Unknown plugin kcptun
```

**Comment by Mygod** [comment]
Check your system settings.

**Comment by aUsernameWoW** [comment]
You may need this: https://github.com/shadowsocks/kcptun-android/issues/12
It requires root permissions

**Comment by john564** [comment]
android 6.0 

EDIT: found the problem, checking notifications showed shadowsocks needed the permission to run secondary app kcptun. Once I allowed it, its working again.

Reproduce.
uninstall and install kcptun. First time shadowsocks+kcptun connection works,
second time, gives error "Unknown plugin kcptun"
Check Notifications shows "Stopped Shadowsocks from launching secondary app kcptun"
when you click kcptun, its asks permission for kcptun to be launched by shadowsocks.
Click allow, and all working again.
