### ISSUE TITLE
Stupid Update

### ISSUE THREAD

**Issue by xiaolugo** [shadowsocks/kcptun-android#18]
Have tried many times. Does not work anyway. Can anyone post the right settings? So Stupid Update!!!!

**Comment by Mygod** [comment]
![image](https://cloud.githubusercontent.com/assets/3511321/24754237/3b3b0f46-1b08-11e7-8e6a-18dcfb37faf7.png)

**Comment by xbh** [comment]
You can read the maual to set your setting.
