### ISSUE TITLE
Can not run on Android 8.0 beta

### ISSUE THREAD

**Issue by zhangzhuoming** [shadowsocks/kcptun-android#19]
This plugin can not run on Android 8.0 beta.pixel xl

**Comment by Mygod** [comment]
If you're talking about Android O preview, we're currently working on bringing these apps to the new version of Android but it's still a work in progress and it's not meant to be used by end users yet. You're welcome to contribute. See here for more info: https://github.com/shadowsocks/shadowsocks-android/pull/1258
