### ISSUE TITLE
建议出一个kcpraw的插件

### ISSUE THREAD

**Issue by lovepocky** [shadowsocks/kcptun-android#20]
> https://github.com/ccsexyz/kcpraw

**Comment by Mygod** [comment]
It seems to me that doing so (kcpraw) is the same as simple-obfs, only slower.

**Comment by lovepocky** [comment]
Thank you for your reply

**Comment by madeye** [comment]
Actually, it's a clever way to avoid QoS, which is one of the limitations of UDP based kcptun.

However, current kcpraw requires dropping RST packets with iptables. On Android, unless you have a rooted device, kcpraw cannot work well.

I think maybe we can take advantage of userland netstack to avoid usage of netfilter? For example, https://github.com/google/netstack. @ccsexyz

**Comment by Mygod** [comment]
@madeye It seems to me that KCP is basically designed to reinvent TCP over UDP so that one can have better control over its parameters. Doing KCP over TCP has little benefits.

Also using netstack seems to require root as well.

**Comment by madeye** [comment]
@Mygod I think it may not be the real TCP? In theory, we can send SYN/ACK packets like UDP packets, which would play tricks with QoS. One limitation is kernel would get confused.

**Comment by Mygod** [comment]
@madeye I see. I'd be curious how well that work.

**Comment by ccsexyz** [comment]
Yet many people, including myself, don't have a rooted device.I don't think it‘s necessary to do so.

**Comment by eromoe** [comment]
+1 for kcpraw plugin. Does it on progress now ?

**Comment by Mygod** [comment]
Please continue the discussions at: https://discourse.shadowsocks.org/t/plugin-request-kcpraw/31

And for progress, I'm not working on it for now and for the foreseeable future so feel free to contribute.
