### ISSUE TITLE
Configuring kcptun android plugin with android-shadowsocks app

### ISSUE THREAD

**Issue by JeffCleverley** [shadowsocks/kcptun-android#25]
Hey, I am having problems with the android plugin.

My kcptun config:

```
{
    "listen": "0.0.0.0:4000",
    "target": "127.0.0.1:6969",
    "key": "<password>",
    "crypt": "salsa20",
    "mode": "fast2",
    "mtu": 1400,
    "sndwnd": 2048,
    "rcvwnd": 2048,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10
}
```

Everything is working fine with QT5 on my mac, see screenshot:

![screen shot 2017-10-28 at 4 16 40 pm](https://user-images.githubusercontent.com/25419360/32132724-938f7634-bbfb-11e7-9ea7-749bb628b53f.png)

but whenever I enable the kcptun plugin for the shadowsocks app with the following config:

`dscp=46;mtu=1350;parityshard=0;mode=fast2;key=<password>;crypt=salsa20`

I have tried setting the android shadowsocks app remote port to both the original 6969 and to the KCPTUN port 4000

Any pointers where I am going wrong please, the only tutorial or documentation I've found for the plugin says:

'configure settings'

And according to the configuration settings in the plugin, as far as I can see everything is okay.

Thanks for your help

**Comment by fwgt** [comment]
Try put remote port=6969 in SS app setting and port=4000 in plugin config settings.

**Comment by Mygod** [comment]
Your configuration clearly does not match.

**Comment by JeffCleverley** [comment]
@fwgt 

Apologies for late reply, been away.

You can't... the Kcptun port automatically sets the SS port, that's why it is blacked out.

@Mygod 

The Kcptun configuration is there, saying it clearly doesn't match was not helpful.

SS works fine with its standard config, so all the passwords and IP addresses are fine. 

If you could point out the mistake on the kcptun configuration then that may be helpful, but otherwise what is the point.

Clearly nothing, I provided my config and SS app set up.

**Comment by john564** [comment]
as OP said, it clearly doesn't match.

Like for example you have parityshard different in each setup, and I can confirm using setting parityshard=0; stops it working.  

 --parityshard value, --ps value  set reed-solomon erasure coding - parityshard (default: 3)
