### ISSUE TITLE
要如何配置呢～

### ISSUE THREAD

**Issue by NetRube** [shadowsocks/kcptun-android#3]
格式是否跟旧版一样～比如分隔符～

**Comment by NetRube** [comment]
我自己试出来了～不过开启后无法关闭节点导致也无法切换节点～

**Comment by lyhiving** [comment]
现在主要是换不了端口，这次4.0的改动是比较大了。
我有个安卓更新后，无法安装就版本，只能用普通版本

**Comment by Mygod** [comment]
@lyhiving Attach logcat please.
