### ISSUE TITLE
提示未知插件

### ISSUE THREAD

**Issue by chengs2035** [shadowsocks/kcptun-android#30]
后台服务启动失败：无法连接远程服务器：未知插件kcptun
我安装的都是最新的了
kcptun-nightly-0.0.6.apk
shadowsocks--universal-4.4.6.apk
不知道要咋搞了。日志啥的咋提供呢？
**是不是手机没有root不能用呢？**
![_20180222002229](https://user-images.githubusercontent.com/12379446/36491822-a83a0862-1766-11e8-84ca-3ecc732091c3.jpg)
shadowsocks-nightly-4.4.5.apk
我将SS的IP跟地址改为服务器的IP跟端口，也是相同的提示。

**Comment by chengs2035** [comment]
shadowsocks-nightly-4.4.5.apk
也是无法用

**Comment by fck-username** [comment]
我也是相同的问题 
另外不用加速比乌龟还慢 谷歌首页都上不去

**Comment by chengs2035** [comment]
我已经解决了，我用的是努比亚的手机，需要在手机管家->权限管理->自启动管理中将kcptun设置为允许启动。，华为手机貌似也有类似的问题。需要设置

**Comment by chengs2035** [comment]
@ryanerwin  我没有三星手机，不知道用不用ROOT，但是正常是不用ROOT的。

**Comment by xuexiaokang** [comment]
这个插件太难用了，简直就是折磨人啊，问题太多，希望早日能改进完成

**Comment by jearton** [comment]
> 我已经解决了，我用的是努比亚的手机，需要在手机管家->权限管理->自启动管理中将kcptun设置为允许启动。，华为手机貌似也有类似的问题。需要设置

我也是努比亚手机，这个方法可以

**Comment by mcoder2014** [comment]
> 我已经解决了，我用的是努比亚的手机，需要在手机管家->权限管理->自启动管理中将kcptun设置为允许启动。，华为手机貌似也有类似的问题。需要设置

中兴-遇到了同样的问题，通过这个方法解决了。

**Comment by mrllik** [comment]
> 我已经解决了，我用的是努比亚的手机，需要在手机管家->权限管理->自启动管理中将kcptun设置为允许启动。，华为手机貌似也有类似的问题。需要设置

是的，为了防止国内全家桶套餐的链式启动，很多家的系统默认都把启动关闭了

**Comment by kerener** [comment]
> 这个插件太难用了，简直就是折磨人啊，问题太多，希望早日能改进完成

这个插件太好用！！！！
直接连外网，白天没问题，晚上打不开网页。用了kcp后youtube能流畅看1080p。

我的配置：
服务器端用默认的，只是-mode  fast3，
android上只配置：mode=fast3就OK！
