### ISSUE TITLE
配合shadowsocks+kcptun插件，使用ipv6为服务器地址，连接上但测试不通

### ISSUE THREAD

**Issue by auroneboss** [shadowsocks/kcptun-android#31]
已经确认，只要使用同一服务器的ipv4为服务器地址，就能成功连接入网络并启动。
而仅使用shadowsocks不使用插件，服务器地址为ipv6地址，同样可以成功连接网络。

**Comment by Mygod** [comment]
Cannot reproduce. Double check your config.

**Comment by maxwellzh** [comment]
@auroneboss 你解决这个问题了吗，我遇到了一样的情况

**Comment by maxwellzh** [comment]
我找到了问题所在:
不要使用目前play store上的0.0.4版本，用https://drive.google.com/file/d/1PoQ4EES3crWXTn8v5t1-l8fA2tzCCigk/view?usp=drivesdk这个是0.0.5nightly，升级后问题解决
