### ISSUE TITLE
You closed this issue without responding properly - kcptun settings don't work.

### ISSUE THREAD

**Issue by JeffCleverley** [shadowsocks/kcptun-android#34]
https://github.com/shadowsocks/kcptun-android/issues/25#issuecomment-401574538

As others have pointed out.

**Comment by JeffCleverley** [comment]
"Try put remote port=6969 in SS app setting and port=4000 in plugin config settings."

This is impossible in the shadowsocks app, as the kcptun settings take precedence. You can't set them to be different.

**Comment by john564** [comment]
@JeffCleverley 
Please don't use parityshard=0

The default is 3.

I can say from testing, setting it to 0 stops it working.

**Comment by Mygod** [comment]
Questions should go to [discourse forum](https://discourse.shadowsocks.org/c/implementations/shadowsocks-android) with tag plugin.
