### ISSUE TITLE
新版本kcp配置不成功 发现remoteaddr无法正确配置

### ISSUE THREAD

**Issue by foxundermoon** [shadowsocks/kcptun-android#37]
更新版本之后 经过多次配置都失败，于是clone源码编译调试。

发现remoteaddr 参数在帮助里隐藏了，之前的配置是 ` remoteaddr=vpshost:kcpport `    界面上远程端口配置 ss的端口忽略就可以正常连接，但是现在在手机上无法正确连接，调试的时候  开启之后kcp进程就会自动断开，不确定是参数问题 还是android版本更新后的问题
```kt
 .filter {
                            !it.startsWith("   --localaddr ") &&
                                    !it.startsWith("   --remoteaddr ") &&
                                    !it.startsWith("   -c ") &&
                                    !it.startsWith("   -V ") &&
                                    !it.startsWith("   --fast-open ") &&
                                    !it.startsWith("   --help,") &&
                                    !it.startsWith("   --version,")
                        }
```
remoteaddr应该是必配项，在帮助里隐藏的用意是什么 捉摸不透

**Comment by catdog** [comment]
尝试将ds替换成datashard,ps换成parityshard.
遇到了同样的问题，摆弄半天连不上,后来尝试这么弄居然正常连上了......._(: 」∠)_

**Comment by catdog** [comment]
mode=fast2;remoteaddr=;dscp=46;crypt=none;parityshard=0;rcvwnd=888;sndwnd=160;key=;datashard=0;nocomp
