### ISSUE TITLE
Issue with plugin when used Wi-Fi instead mobile connection

### ISSUE THREAD

**Issue by r4sas** [shadowsocks/kcptun-android#38]
Hi.
I have tested shadowsocks with kcptun plugin on few devices and everywhere I had problem with connection if used Wi-Fi.
When connected to mobile internet shadowsocks works and traffic proxified correctly.

Is it a bug or that is expected behavior?

**Comment by Mygod** [comment]
kcptun requires UDP to work.

>

**Comment by r4sas** [comment]
I haven't problems with it because I use KCPTUN on PC with Windows on some as Wi-Fi network.

**Comment by Mygod** [comment]
Cannot reproduce. Probably Wi-Fi router issue.
