### ISSUE TITLE
Stops working on connection change

### ISSUE THREAD

**Issue by Mygod** [shadowsocks/kcptun-android#41]
Steps to reproduce:

1. Connect
2. Test connection (working)
3. Turn off and on WiFi or mobile data
4. Test again (stops working)
5. Restart profile
6. Test again (working)

**Comment by madeye** [comment]
Set `autoexpire` to 10 and try again. It's expected kcptun cannot detect network changing correctly.

**Comment by Mygod** [comment]
kcptun does check for connection closes, e.g. [here](https://github.com/shadowsocks/kcptun/blob/178390ef80d786c0064401363d3f4a96bb4eb3b6/client/main.go#L571). Maybe we should investigate why that isn't working.

**Comment by Mygod** [comment]
Upon further inspection, this issue seems to only occur in VPN mode. Proxy only mode does not have the same issue. Maybe another `Dial` call we missed perhaps?

**Comment by Mygod** [comment]
Okay. It turns out the problem was caused by `bindSocket`. If we change it back to `protect`, everything will be fine.

**Comment by Mygod** [comment]
Okay after a lot of digging around, I might have to agree with you about sending a signal. I also created an issue at upstream since they also have similar issue there: https://github.com/xtaci/kcptun/issues/642 But at this point, we might as well just use QUIC, where there is connection migration, honestly. So let's just say `autoexpire` is good enough for now.

Also I'm seeing `SetDSCP: invalid connection` on this build. Thoughts?

**Comment by madeye** [comment]
I saw `SetDSCP: invalid connection` as well. Not sure if it's an Android specific issue that we cannot set DSCP on that socket.

But it'd not be a problem, since most of NAT devices would just ignore and drop DSCP.
