### ISSUE TITLE
Will not work with Q

### ISSUE THREAD

**Issue by prajwalkoirala23** [shadowsocks/kcptun-android#43]
Didn't work with Android Q, no error just won't work 

Was working perfectly before I updated

**Comment by seiginonakama** [comment]
me too, show the msg "后台服务启动失败: libss-local exists too fast(exit code: 255)"

**Comment by ggggxiaolong** [comment]
可以试一下[app](https://github.com/ggggxiaolong/kcptun-android/releases)
pixel AndroidQ beta5 测试可以运行

**Comment by hanzhen1135** [comment]
When I execture ssr with tcptun  and show the msg "后台服务启动失败: libss-local exists too fast(exit code: 255)",I find the logcat error log.

09-24 12:07:37.231  7726  7726 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-24 12:07:37.231  7726  7726 F DEBUG   : Build fingerprint: 'Xiaomi/cepheus/cepheus:10/QKQ1.190716.003/V10.4.0.7.QFACNXM:user/release-keys'
09-24 12:07:37.231  7726  7726 F DEBUG   : Revision: '0'
09-24 12:07:37.231  7726  7726 F DEBUG   : ABI: 'arm64'
09-24 12:07:37.231  7726  7726 F DEBUG   : Timestamp: 2019-09-24 12:07:37+0800
09-24 12:07:37.231  7726  7726 F DEBUG   : pid: 7715, tid: 7715, name: libkcptun.so  >>> /data/app/com.github.shadowsocks.plugin.kcptun--fvxz605mYjT-RGNu6sLkQ==/lib/arm64/libkcptun.so <<<
09-24 12:07:37.231  7726  7726 F DEBUG   : uid: 10313
09-24 12:07:37.231  7726  7726 F DEBUG   : signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
09-24 12:07:37.231  7726  7726 F DEBUG   : Abort message: 'error: "/data/app/com.github.shadowsocks.plugin.kcptun--fvxz605mYjT-RGNu6sLkQ==/lib/arm64/libkcptun.so": executable's TLS segment is underaligned: alignment is 8, needs to be at least 64 for ARM64 Bionic'
09-24 12:07:37.231  7726  7726 F DEBUG   :     x0  0000000000000000  x1  0000000000001e23  x2  0000000000000006  x3  0000007ff62abcc0
09-24 12:07:37.231  7726  7726 F DEBUG   :     x4  0000008000000000  x5  0000008000000000  x6  0000008000000000  x7  0000000000000020
09-24 12:07:37.231  7726  7726 F DEBUG   :     x8  00000000000000f0  x9  fc1e382ef312ddb7  x10 0000000000000001  x11 0000000000000000
09-24 12:07:37.231  7726  7726 F DEBUG   :     x12 fffffff0ffffffdf  x13 000000005d899689  x14 000a0377bb1b0400  x15 0000a69cfea999b0
09-24 12:07:37.231  7726  7726 F DEBUG   :     x16 0000000000000030  x17 0000000000000000  x18 00000070461ee000  x19 0000000000001e23
09-24 12:07:37.231  7726  7726 F DEBUG   :     x20 0000000000001e23  x21 00000000ffffffff  x22 0000007046c4e5b0  x23 0000007045a6ad00
09-24 12:07:37.231  7726  7726 F DEBUG   :     x24 0000007046c4e5a0  x25 0000007046c4e000  x26 0000007046c4e9e8  x27 0000007046c4e9a0
09-24 12:07:37.231  7726  7726 F DEBUG   :     x28 0000007ff62acea8  x29 0000007ff62abd60
09-24 12:07:37.231  7726  7726 F DEBUG   :     sp  0000007ff62abca0  lr  0000007046c188a8  pc  0000007046c188d4
09-24 12:07:37.232  7726  7726 F DEBUG   : 
09-24 12:07:37.232  7726  7726 F DEBUG   : backtrace:
09-24 12:07:37.232  7726  7726 F DEBUG   :       #00 pc 00000000000e58d4  /apex/com.android.runtime/bin/linker64 (__dl_abort+160) (BuildId: 288df7ff2240699d1a32b99f3c2b9e5f)
09-24 12:07:37.232  7726  7726 F DEBUG   :       #01 pc 00000000001072c0  /apex/com.android.runtime/bin/linker64 (__dl__ZN15StaticTlsLayout27reserve_exe_segment_and_tcbEPK10TlsSegmentPKc+268) (BuildId: 288df7ff2240699d1a32b99f3c2b9e5f)
09-24 12:07:37.232  7726  7726 F DEBUG   :       #02 pc 0000000000053404  /apex/com.android.runtime/bin/linker64 (__dl__Z27linker_setup_exe_static_tlsPKc+68) (BuildId: 288df7ff2240699d1a32b99f3c2b9e5f)
09-24 12:07:37.232  7726  7726 F DEBUG   :       #03 pc 000000000004e3f4  /apex/com.android.runtime/bin/linker64 (__dl__ZL29__linker_init_post_relocationR19KernelArgumentBlockR6soinfo+3144) (BuildId: 288df7ff2240699d1a32b99f3c2b9e5f)
09-24 12:07:37.232  7726  7726 F DEBUG   :       #04 pc 000000000004d750  /apex/com.android.runtime/bin/linker64 (__dl___linker_init+396) (BuildId: 288df7ff2240699d1a32b99f3c2b9e5f)
09-24 12:07:37.232  7726  7726 F DEBUG   :       #05 pc 0000000000054a54  /apex/com.android.runtime/bin/linker64 (__dl__start+4) (BuildId: 288df7ff2240699d1a32b99f3c2b9e5f)
