### ISSUE TITLE
Pls update kcptun plugin，it can not work with kcptun 20191107 server 

### ISSUE THREAD

**Issue by cdb0y511** [shadowsocks/kcptun-android#47]
the relate issue
https://github.com/xtaci/kcptun/issues/736
After update server to kcptun 20191107. it cannot work anymore.
https://github.com/xtaci/kcptun/releases/tag/v20191107

It only work with  kcptun 20190924 and below.
pls update the plugin

**Comment by rogers0** [comment]
I tested kcptun 20200409 on server side, and it still works well with current kcptun android version

**Comment by cdb0y511** [comment]
thx, anyway. this is an old bug. fixed already.
