### ISSUE TITLE
是不是安装之后，什么东西都看不到的？在后台运行的吗？

### ISSUE THREAD

**Issue by kentcc88** [shadowsocks/kcptun-android#48]
是不是安装之后，什么东西都看不到的？在后台运行的吗？

**Comment by kentcc88** [comment]
没啥用，ss客户端设置这插件之后也无法连接，啥提示也没有，按理说应该要求我修改kcptun的端口，可是毫无反应

**Comment by andronoob** [comment]
安装后，Android这边的ss端口就是kcptun服务端的端口。两边几个参数搞对了就可以用了。还有就是UDP DNS不能开。

**Comment by 907597029** [comment]
kcptun是插件 所以没有显示app 在shadowsocks最下方有个禁用插件 改成kcptun 其中改一下kcptun的配置就行

shadowsocks的远程端口改成服务器kcptun的端口 密码为shadowsocks的密码

mode=fast;dscp=0;crypt=aes;parityshard=3;rcvwnd=512;key=very fast;sndwnd=512;mtu=1350;datashard=10

记得配置一下kcptun里面的设置 没压缩传输的就删除nocomp这一条

**Comment by catdog** [comment]
启用kcptun插件后配置记得里加
remoteaddr=<IP:PORT>
指定服务器地址跟端口
