### ISSUE TITLE
你好，请问怎么内置到shadowsocks-android项目中而不是单独安装？

### ISSUE THREAD

**Issue by FynnJason** [shadowsocks/kcptun-android#51]
你好，我想请问一个问题，如何将kcptun-android内置到shadowsocks-android中，而不是将kcptun单独安装到手机上？

**Comment by Mygod** [comment]
Shadowsocks will crash if you attempt to do that.

**Comment by FynnJason** [comment]
@Mygod 根据我查看以往的Issues，我发现有人说旧版本的shadowsocks-android是内置kcptun的，那为什么当时可以，而现在不可以了呢？
