### ISSUE TITLE
The ss-android with kcptun plugin can not shut down again.

### ISSUE THREAD

**Issue by xseven007** [shadowsocks/kcptun-android#9]
The ss-android with kcptun plugin can not be shutted down again after I have update it to 0.03.

**Comment by Mygod** [comment]
Hmm yeah please wait patiently or use 0.0.2 for now. This issue is solved from 0.0.1 to 0.0.3 if you're using the latest beta branch of shadowsocks-android. 😂

**Comment by xseven007** [comment]
Hi guy. I think I am a dog who always "zuo" die .....

**Comment by Mygod** [comment]
Update to shadowsocks-android 4.0.1 to see this issue gone for good.
